apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "tinylicious.fullname" . }}
  labels:
    app: {{ template "tinylicious.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Values.name }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  config.json: |
    {
        "logger": {
            "colorize": false,
            "morganFormat": "short",
            "json": true,
            "level": "info",
            "timestamp": false,
            "label": "winston"
        },
        "mongo": {
            "collectionNames": {
                "deltas": "deltas",
                "documents": "documents",
                "partitions": "partitions",
                "tenants": "tenants",
                "nodes": "nodes",
                "reservations": "reservations",
                "scribeDeltas": "scribeDeltas"
            }
        },
        "foreman": {
            "permissions": {
                "paparazziQueue": ["snapshot", "spell", "intel", "translation"],
                "augloopQueue": ["augmentation"],
                "headlessQueue": ["chain-snapshot", "chain-intel", "chain-translation", "chain-spell", "chain-cache"]
            }
        },
        "alfred": {
            "maxMessageSize": "16KB",
            "maxNumberOfClientsPerDocument": 1000000,
            "restJsonSize": "1mb"
        },
        "storage": "/var/lib/tinylicious/snapshots",
        "db": {
            "inMemory": true,
            "path": "/var/lib/tinylicious/db"
        },
        "error": {
            "track": false,
            "endpoint" : ""
        }
    }
