kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "tinylicious.fullname" . }}
  labels:
    app: {{ template "tinylicious.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
