apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "tinylicious-gateway.fullname" . }}
  labels:
    app: {{ template "tinylicious-gateway.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Values.name }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  config.json: |
    {
        "logger": {
            "colorize": false,
            "morganFormat": "short",
            "json": true,
            "level": "info",
            "timestamp": false,
            "label": "winston"
        },
        "gateway": {
            "maxMessageSize": "16KB",
            "restJsonSize": "1mb",
            "key": "{{ .Values.key }}",
            "url": "https://{{ .Values.host }}"
        },
        "tinylicious": "{{ .Values.tinylicious }}",
        "npm": "https://unpkg.com/",
        "error": {
            "track": false
        }
    }
