apiVersion: v1
kind: Service
metadata:
  name: {{ template "tinylicious-gateway.fullname" . }}
  labels:
    app: {{ template "tinylicious-gateway.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: ui
  selector:
    app: {{ template "tinylicious-gateway.name" . }}
    release: {{ .Release.Name }}
